CREATE TABLE IF NOT EXISTS users (
  full_name VARCHAR(64) NOT NULL,
  username VARCHAR(32) UNIQUE NOT NULL,
  email VARCHAR(64) PRIMARY KEY,
  password VARCHAR(128) NOT NULL,
  type VARCHAR(64) NOT NULL
)

CREATE TABLE IF NOT EXISTS members (
  email VARCHAR(64) REFERENCES users (email)
  ON UPDATE CASCADE 
  ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED
)

CREATE TABLE IF NOT EXISTS administrator (
  email VARCHAR(64) REFERENCES users (email)
  ON UPDATE CASCADE
  ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED
)

CREATE TABLE IF NOT EXISTS category (
  category VARCHAR(32) PRIMARY KEY
) 

CREATE TABLE IF NOT EXISTS activity (
  activity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter VARCHAR(64) REFERENCES users(email)
  ON UPDATE CASCADE ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED,
  category VARCHAR(32) REFERENCES category(category),
  activity_name VARCHAR(128) NOT NULL,
  start_datetime DATETIME NOT NULL,
  end_datetime DATETIME NOT NULL CHECK start_datetime <= end_datetime,
  venue VARCHAR(128) NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity >= 0)
)

CREATE TABLE IF NOT EXISTS join (
  activity_id INT REFERENCES activity(activity_id),
  participant VARCHAR(64) REFERENCES users(email),
  rating FLOAT(5) CHECK (rating >= 1 AND rating <= 5).
  PRIMARY KEY (activity_id,participant)
)

CREATE TABLE IF NOT EXISTS review (
  activity_id INT REFERENCES activity(activity_id),
  timestamp DATETIME NOT NULL,
  participant VARCHAR(64) REFERENCES users(email),
  comment VARCHAR(4096) NOT NULL,
  PRIMARY KEY (activity_id,timestamp,participant)
)

CREATE TABLE IF NOT EXISTS report (
  submitter VARCHAR(64) REFERENCES users(email),
  timestamp DATETIME NOT NULL,
  user VARCHAR(64) REFERENCES users(email),
  comment VARCHAR(4096) NOT NULL,
  severity VARCHAR(6) NOT NULL,
  PRIMARY KEY (submitter,timestamp)
)